# Generated by Django 4.0.6 on 2022-07-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_productaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productaccount',
            options={'verbose_name': 'اکانت', 'verbose_name_plural': 'اکانت های محصولات'},
        ),
        migrations.AlterField(
            model_name='productaccount',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='productaccount',
            name='passworld',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='پسورد'),
        ),
        migrations.AlterField(
            model_name='productaccount',
            name='ramz',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='رمز بازی (اضافه))'),
        ),
        migrations.AlterField(
            model_name='productaccount',
            name='user_name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='نام کاربری'),
        ),
    ]
